# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeZ_cpp <- function(zList, theta, groups) {
    .Call(`_gfe_computeZ_cpp`, zList, theta, groups)
}

computeZ_res_cpp <- function(zList, theta) {
    .Call(`_gfe_computeZ_res_cpp`, zList, theta)
}

computeAlpha_cpp <- function(Z, groups) {
    .Call(`_gfe_computeAlpha_cpp`, Z, groups)
}

computeSigma_cpp <- function(zList, theta, groupR) {
    .Call(`_gfe_computeSigma_cpp`, zList, theta, groupR)
}

computeResiduals_cpp <- function(zList, theta, groups, alpha) {
    .Call(`_gfe_computeResiduals_cpp`, zList, theta, groups, alpha)
}

gfeObj_cpp <- function(Z, groups) {
    .Call(`_gfe_gfeObj_cpp`, Z, groups)
}

wgfeObj_cpp <- function(Z, groups) {
    .Call(`_gfe_wgfeObj_cpp`, Z, groups)
}

wgfeObj_bs_cpp <- function(z, b, group, sigg, sig) {
    .Call(`_gfe_wgfeObj_bs_cpp`, z, b, group, sigg, sig)
}

slopeGradGFE_cpp <- function(z, group) {
    .Call(`_gfe_slopeGradGFE_cpp`, z, group)
}

calcGroupSlopes_cpp <- function(zList, groups) {
    .Call(`_gfe_calcGroupSlopes_cpp`, zList, groups)
}

computeXXY_demeaned_cpp <- function(zList, wgroups) {
    .Call(`_gfe_computeXXY_demeaned_cpp`, zList, wgroups)
}

wc_fp_cpp <- function(zList, b, wgroups, XX_list, y_list, gee) {
    .Call(`_gfe_wc_fp_cpp`, zList, b, wgroups, XX_list, y_list, gee)
}

wc_fp_bs_cpp <- function(z, b, s, groups, XX_demeaned, y_demeaned, sigs) {
    .Call(`_gfe_wc_fp_bs_cpp`, z, b, s, groups, XX_demeaned, y_demeaned, sigs)
}

wc_fp_loop_cpp <- function(zList, wgroups, XX_list, y_list, gee, tol = 1e-13, max_iter = 1000L) {
    .Call(`_gfe_wc_fp_loop_cpp`, zList, wgroups, XX_list, y_list, gee, tol, max_iter)
}

gfeJump_cpp <- function(replaceR, i, grR, Z_N, alpha_N) {
    .Call(`_gfe_gfeJump_cpp`, replaceR, i, grR, Z_N, alpha_N)
}

wgfe_loop_res_cpp <- function(z, b0, sig0, wgroups, sigsg, tol = 1e-13, maxiter = 1000L) {
    .Call(`_gfe_wgfe_loop_res_cpp`, z, b0, sig0, wgroups, sigsg, tol, maxiter)
}

wgfeJump_cpp <- function(replace, i, gr, Z_, alpha_) {
    .Call(`_gfe_wgfeJump_cpp`, replace, i, gr, Z_, alpha_)
}

wgfeJump_bs_cpp <- function(replace, i, gr_in, Z, alpha, sigs, sig) {
    .Call(`_gfe_wgfeJump_bs_cpp`, replace, i, gr_in, Z, alpha, sigs, sig)
}

assignGroups_cpp <- function(zList, theta, alpha) {
    .Call(`_gfe_assignGroups_cpp`, zList, theta, alpha)
}

assignGroups_wgfe_cpp <- function(zList, theta, Alpha, SigmaG) {
    .Call(`_gfe_assignGroups_wgfe_cpp`, zList, theta, Alpha, SigmaG)
}

assignGroups_res_cpp <- function(Z, alpha, sigsg, sig0) {
    .Call(`_gfe_assignGroups_res_cpp`, Z, alpha, sigsg, sig0)
}

refineGroups_cpp <- function(zList, wgroups, heterogeneous, method) {
    .Call(`_gfe_refineGroups_cpp`, zList, wgroups, heterogeneous, method)
}

refineGroups_res_cpp <- function(zList, wgroups, sig0, sigsg) {
    .Call(`_gfe_refineGroups_res_cpp`, zList, wgroups, sig0, sigsg)
}

localJump_cpp <- function(wgroups, Z, alpha, gee, method, minSize = 1L) {
    .Call(`_gfe_localJump_cpp`, wgroups, Z, alpha, gee, method, minSize)
}

se_cpp <- function(Y, X, theta0, groupR, alpha0, sigma0, t) {
    .Call(`_gfe_se_cpp`, Y, X, theta0, groupR, alpha0, sigma0, t)
}

seHet_cpp <- function(zList, theta, groupR, alpha0) {
    .Call(`_gfe_seHet_cpp`, zList, theta, groupR, alpha0)
}

random_move_cpp <- function(wgroups, gee, Seq, n) {
    .Call(`_gfe_random_move_cpp`, wgroups, gee, Seq, n)
}

computeZ_unbalanced_cpp <- function(zList, theta, groups) {
    .Call(`_gfe_computeZ_unbalanced_cpp`, zList, theta, groups)
}

computeAlpha_unbalanced_cpp <- function(Zall, groups) {
    .Call(`_gfe_computeAlpha_unbalanced_cpp`, Zall, groups)
}

computeSigma_unbalanced_cpp <- function(Zall, alpha, groups) {
    .Call(`_gfe_computeSigma_unbalanced_cpp`, Zall, alpha, groups)
}

gfeObj_unbalanced_cpp <- function(Zall, groups) {
    .Call(`_gfe_gfeObj_unbalanced_cpp`, Zall, groups)
}

wgfeObj_unbalanced_cpp <- function(Zall, groups) {
    .Call(`_gfe_wgfeObj_unbalanced_cpp`, Zall, groups)
}

slopeGradGFE_unbalanced_cpp <- function(z, group) {
    .Call(`_gfe_slopeGradGFE_unbalanced_cpp`, z, group)
}

computeXXY_demeaned_unbalanced_cpp <- function(zList, wgroups) {
    .Call(`_gfe_computeXXY_demeaned_unbalanced_cpp`, zList, wgroups)
}

wc_fp_unbalanced_cpp <- function(zList, b, wgroups, XX_list, y_list, gee) {
    .Call(`_gfe_wc_fp_unbalanced_cpp`, zList, b, wgroups, XX_list, y_list, gee)
}

wc_fp_loop_unbalanced_cpp <- function(zList, wgroups, XX_list, y_list, gee, tol = 1e-13, max_iter = 1000L) {
    .Call(`_gfe_wc_fp_loop_unbalanced_cpp`, zList, wgroups, XX_list, y_list, gee, tol, max_iter)
}

calcGroupSlopes_unbalanced_cpp <- function(zList, groups) {
    .Call(`_gfe_calcGroupSlopes_unbalanced_cpp`, zList, groups)
}

gfeJump_unbalanced_cpp <- function(replaceR, i, grR, Z_N) {
    .Call(`_gfe_gfeJump_unbalanced_cpp`, replaceR, i, grR, Z_N)
}

wgfeJump_unbalanced_cpp <- function(replaceR, i, grR, Z_N, alpha_N) {
    .Call(`_gfe_wgfeJump_unbalanced_cpp`, replaceR, i, grR, Z_N, alpha_N)
}

localJump_unbalanced_cpp <- function(wgroups_, Z, gee_, method) {
    .Call(`_gfe_localJump_unbalanced_cpp`, wgroups_, Z, gee_, method)
}

localJump_het_unbalanced_cpp <- function(wgroups, zList, gee, method) {
    .Call(`_gfe_localJump_het_unbalanced_cpp`, wgroups, zList, gee, method)
}

assignGroups_unbalanced_cpp <- function(zList, theta, alpha) {
    .Call(`_gfe_assignGroups_unbalanced_cpp`, zList, theta, alpha)
}

assignGroups_wgfe_unbalanced_cpp <- function(zList, theta, Alpha, SigmaG) {
    .Call(`_gfe_assignGroups_wgfe_unbalanced_cpp`, zList, theta, Alpha, SigmaG)
}

refineGroups_unbalanced_cpp <- function(zList, wgroups, heterogeneous, method) {
    .Call(`_gfe_refineGroups_unbalanced_cpp`, zList, wgroups, heterogeneous, method)
}

se_unbalanced_cpp <- function(Y, X, theta0, groupR, alpha0, sigma0, t) {
    .Call(`_gfe_se_unbalanced_cpp`, Y, X, theta0, groupR, alpha0, sigma0, t)
}

seHet_unbalanced_cpp <- function(zList, theta0, groupR, alpha0) {
    .Call(`_gfe_seHet_unbalanced_cpp`, zList, theta0, groupR, alpha0)
}

